### ISSUE TITLE
Tests for chamber array fun

### ISSUE THREAD

**Issue by cpaniaguam** [brown-ccv/Chamber.jl#248]
Design tests for the version of `chamber` that takes in arrays as inputs.

**Comment by cpaniaguam** [comment]
Initial thoughts:
- [ ] Generate output for two runs using the scalar version of `chamber` for two different sets of inputs
- [ ] Use build array inputs from the set of inputs used to generate the test output
- [ ] Check output files are created
- [ ] Compare output files from array version against results from scalar version

**Comment by CallieHsu** [comment]
@cpaniaguam Here are updates based on your comment:
https://github.com/brown-ccv/Chamber.jl/commit/ed83774331ca236ef9efb2f0c17f89c97c9edeb4


> Initial thoughts:
> 
> * [ ]  Generate output for two runs using the scalar version of `chamber` for two different sets of inputs
> * [ ]  Use build array inputs from the set of inputs used to generate the test output
> * [ ]  Check output files are created
> * [ ]  Compare output files from array version against results from scalar version
